In [1]:
import numpy as np

# Q1: Questions on Basic NumPy Array

(a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])

In [2]:
arr = np.array([1, 2, 3, 6, 4, 5])

arr[::-1]


array([5, 4, 6, 3, 2, 1])

(b) Flatten the NumPy arr: array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]]) using any two
NumPy in-built methods

In [3]:
array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]]) 


print("before flattening : \n",array1,"\n\nAfter Flattening :",array1.flatten())


before flattening : 
 [[1 2 3]
 [2 4 5]
 [1 2 3]] 

After Flattening : [1 2 3 2 4 5 1 2 3]


(c) Compare the following numpy arrays:

In [4]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])


print(np.array_equal(arr1,arr2),(arr1==arr2).all())

True True


(d) Find the most frequent value and their indice(s) in the following arrays:

In [5]:
from statistics import mode

x = np.array([1,2,3,4,5,1,2,1,1,1])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

print(mode(x)," is at ",np.where(x==mode(x)),"\n\n",mode(y)," is at ", np.where(y==mode(y)))


1  is at  (array([0, 5, 7, 8, 9]),) 

 1  is at  (array([0, 1, 2]),)


In [6]:
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')

print("Flatten sum : ",np.sum(gfg),"\n\nColumn wise sum : ",np.sum(gfg,axis=0),"\n\nRow wise sum : \n",np.sum(gfg,axis=1))

Flatten sum :  45 

Column wise sum :  [[20  9 16]] 

Row wise sum : 
 [[14]
 [16]
 [15]]


In [7]:
n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]])

print("Sum : ",sum(np.diag(n_array)),"\n\nEigen Vector : \n",np.linalg.eig(n_array),"\n\nEigenValue : ",np.linalg.eigvals(n_array),"\n\nInverse matrix : \n",np.linalg.inv(n_array),"\n\nDeterminant : ",np.linalg.det(n_array))



Sum :  176 

Eigen Vector : 
 (array([98.16835147, 28.097044  , 49.73460452]), array([[ 0.4574917 ,  0.34637121, -0.15017693],
       [ 0.28447814, -0.72784061, -0.4852124 ],
       [ 0.84248058,  0.59184038,  0.8614034 ]])) 

EigenValue :  [98.16835147 28.097044   49.73460452] 

Inverse matrix : 
 [[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]] 

Determinant :  137180.0000000001


In [8]:
p =np.array([[1, 2], [2, 3]])
q =np.array([[4, 5], [6, 7]])


print("The multiplication of the two matrices is : \n",np.dot(p,q),"\n\n","The covariance is : \n",np.cov(np.dot(p,q)))




The multiplication of the two matrices is : 
 [[16 19]
 [26 31]] 

 The covariance is : 
 [[ 4.5  7.5]
 [ 7.5 12.5]]


In [9]:
p1 = ([[1, 2], [2, 3], [4, 5]])
q1 = ([[4, 5, 1], [6, 7, 2]])


print("The multiplication of the two matrices is : \n",np.dot(p1,q1),"\n\n","The covariance is : \n",np.cov(np.dot(p1,q1)))



The multiplication of the two matrices is : 
 [[16 19  5]
 [26 31  8]
 [46 55 14]] 

 The covariance is : 
 [[ 54.33333333  89.16666667 158.83333333]
 [ 89.16666667 146.33333333 260.66666667]
 [158.83333333 260.66666667 464.33333333]]


In [10]:

x = [[2, 3, 4], [3, 2, 9]]
y = [[1, 5, 0], [5, 10, 3]]

print("Inner Product : \n",np.inner(x,y),"\n\n","Outer Product : \n",np.outer(x,y),"\nCartesian product : \n")

Inner Product : 
 [[17 52]
 [13 62]] 

 Outer Product : 
 [[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]] 
Cartesian product : 



# Q2: Based on NumPy Mathematics and Statistics

In [11]:
array = np.array([[1, -2, 3],[-4, 5, -6]])
array2 = array.flatten()


print("i. The absolute Values are : \n",np.absolute(array))


i. The absolute Values are : 
 [[1 2 3]
 [4 5 6]]


In [12]:
print("ii. 25th percentile : ",np.percentile(array2,25),"\n50th percentile : ",np.percentile(array2,50),"\n75th percentile : ",np.percentile(array2,75))

ii. 25th percentile :  -3.5 
50th percentile :  -0.5 
75th percentile :  2.5


In [13]:
print("iii. mean of rows : ",np.mean(array,axis=0) , "\nmean of columns : ",np.mean(array,axis=1))

iii. mean of rows :  [-1.5  1.5 -1.5] 
mean of columns :  [ 0.66666667 -1.66666667]


In [14]:
print("median of rows : ",np.median(array,axis=0) , "\nmedian of columns : ",np.median(array,axis=1))

median of rows :  [-1.5  1.5 -1.5] 
median of columns :  [ 1. -4.]


In [15]:
print("Standard deviation of rows : ",np.std(array,axis=0) , "\nStandard deviation of columns : ",np.std(array,axis=1))

Standard deviation of rows :  [2.5 3.5 4.5] 
Standard deviation of columns :  [2.05480467 4.78423336]


In [16]:
a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0])

In [17]:
print("The floor value of the array is : ",np.floor(a),"\nThe ceiling value of the array is : ",np.ceil(a),"\nThe truncated value of teh array is : ",np.trunc(a),"\nThe rounded value of the array is : ",np.round(a))

The floor value of the array is :  [-2. -2. -1.  0.  1.  1.  3.] 
The ceiling value of the array is :  [-1. -1. -0.  1.  2.  2.  3.] 
The truncated value of teh array is :  [-1. -1. -0.  0.  1.  1.  3.] 
The rounded value of the array is :  [-2. -2. -0.  0.  2.  2.  3.]


# Q3: Based on Searching and Sorting

In [18]:
array = np.array([10, 52, 62, 16, 16, 54, 453])

ab=np.sort(array)

print(ab,np.where(ab))

[ 10  16  16  52  54  62 453] (array([0, 1, 2, 3, 4, 5, 6]),)


In [19]:
print("iii. smallest numbers are :")

for i in range(4):
    print(ab[i])
    

iii. smallest numbers are :
10
16
16
52


In [20]:
print("iv. 5 largest numbers are :")

for i in range(5):
    
    print(ab[i+2])


iv. 5 largest numbers are :
16
52
54
62
453


In [21]:
array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])

arrInt = np.array(array , dtype=int)
arrFloat = np.array(array , dtype=float) 


In [22]:
print("Integers are : ",arrInt,"\nFloat elements are : ",arrFloat)

Integers are :  [1 1 2 2 3 2] 
Float elements are :  [1.  1.2 2.2 2.  3.  2. ]


(a)

In [23]:

from matplotlib.image import imread

def img_to_array(path):
    img = imread(path)
    print(img)
    

In [24]:

c=img_to_array("Desktop/STUDY MATERIAL/Screen shots and wallpapers/images.jpeg")
z=np.array(c)

z

[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]


array(None, dtype=object)